### PR TITLE
Chobby graphics settings presets 

### PR DESCRIPTION
**Pull request by dvr333**
* Increased ultra to maximum values 
* Removed some non-graphical settings.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
These aren't the settings used by the graphics options. Also, the non-graphics settings are quite important for settings to function correctly. The settings menu settings are here https://github.com/Spring-Chobby/Chobby/blob/master/LuaMenu/configs/gameConfig/zk/settingsMenu.lua

**Comment by dvr333** [comment]
Oh, then what did I propose to change?

**Comment by GoogleFrog** [comment]
springsettings3.lua is the base settings used for ingame. I don't think the rest do anything at the moment.

**Comment by dvr333** [comment]
It seems like springsettings3.lua always overrides any other settings on launch, no matter what. My settings work when explicitly set, but they get overridden as soon as Chobby re-launches.

**Pull request merged**
