### PR TITLE
Adding Cursed Campaign

### PR DESCRIPTION
**Pull request by azaremoth**
1) I did add a tiny alpha-state campaign (this was tons of word to do for the game's code) for the cursed. To do so I had to make campaign folder configurable by the gams's config.
2) I did add a nil check for the api_discord_handler.lua to avoid errors

### CODE REVIEW

**Comment by silentwings** [comment]
Isn't this repo meant to be free of game specific stuff?!

**Comment by gajop** [comment]
Hey, sorry for the delay, was very busy.
Gave it a glance now, and it seems to be touching ZK stuff, LuaMenu/configs/gameConfig/zk/ so I cannot merge this as it might be breaking ZK related things.

**Comment by azaremoth** [comment]
Hi Gajo,

It should actually not be touching ZeroK. I made the ZeroK links standard in all pieces of code. Anyway, I will check the code at home. Possibly there is something unintended...

Cheers,
Jan
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 14.03.19, 01:03, Gajo Petrovic <notifications@github.com> schrieb:
Hey, sorry for the delay, was very busy.
Gave it a glance now, and it seems to be touching ZK stuff, LuaMenu/configs/gameConfig/zk/ so I cannot merge this as it might be breaking ZK related things.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Spring-Chobby/Chobby","title":"Spring-Chobby/Chobby","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Spring-Chobby/Chobby"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gajop in #461: Hey, sorry for the delay, was very busy.\r\nGave it a glance now, and it seems to be touching ZK stuff, LuaMenu/configs/gameConfig/zk/ so I cannot merge this as it might be breaking ZK related things."}],"action":{"name":"View Pull Request","url":"https://github.com/Spring-Chobby/Chobby/pull/461#issuecomment-472653016"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Spring-Chobby/Chobby/pull/461#issuecomment-472653016",
"url": "https://github.com/Spring-Chobby/Chobby/pull/461#issuecomment-472653016",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gajop** [comment]
Closing PR due to unresolved conflicts. Seems to still have those issues I mentioned before. Check the changes tab on GitHub.

**Comment by azaremoth** [comment]
Sure. As I understood from the comments, no game specific content should be included in the Chobby repository. Thus I did a fork.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 19.06.19, 12:05, Gajo Petrovic <notifications@github.com> schrieb:
Closing PR due to unresolved conflicts. Seems to still have those issues I mentioned before. Check the changes tab on GitHub.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by gajop** [comment]
> As I understood from the comments, no game specific content should be included in the Chobby repository.

This is incorrect. Game specific content can be included in this repository, like it is done here: https://github.com/Spring-Chobby/Chobby/tree/master/LuaMenu/configs/gameConfig

**Pull request closed without merging**
