### PR TITLE
ZK campaign handler

### PR DESCRIPTION
**Pull request by KingRaptor**
Widget for handling ZK campaign(s), plus the necessary changes to Chobby to support it (i18n file, `gameConfig/zk/singleplayerMenu.lua` and a tweak to Chili Image class). Should be merge-ready.

Includes Chili VN as library and a music player widget. Campaigns sold separately.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Is this intended for merging now?

**Comment by GoogleFrog** [comment]
Also, if we pull it and make a release soon should the campaign tab be commented out? Is it complete enough that you want general feedback?

**Comment by KingRaptor** [comment]
I don't have a campaign actually ready to put in and it may take a while to prepare it (probably this weekend), so might be best to leave it unmerged or comment out the menu entry for the upcoming release. 
(Though given how WIP everything is a campaign menu that does nothing may not a problem?)

**Comment by gajop** [comment]
As long as it doesn't break anything or cause crashes, I'd rather have it merged now, as that'll make continuing work on it easier.

**Pull request merged**
